# Generated by Django 3.2 on 2021-05-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('gameid', models.AutoField(db_column='gameID', primary_key=True, serialize=False)),
                ('gamename', models.CharField(db_column='gameName', max_length=50)),
                ('datereleased', models.DateField(blank=True, db_column='dateReleased', null=True)),
                ('gamedescription', models.CharField(blank=True, db_column='gameDescription', max_length=500, null=True)),
            ],
            options={
                'db_table': 'game',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gamegenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'gamegenre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genreid', models.AutoField(db_column='genreID', primary_key=True, serialize=False)),
                ('genre', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'genre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Playstore',
            fields=[
                ('playstorerow', models.AutoField(db_column='playStoreRow', primary_key=True, serialize=False)),
                ('gameid', models.IntegerField(db_column='gameID')),
                ('gameprice', models.DecimalField(db_column='gamePrice', decimal_places=2, max_digits=18)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('dateadded', models.DateField(blank=True, db_column='dateAdded', null=True)),
            ],
            options={
                'db_table': 'playstore',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Playstorehistory',
            fields=[
                ('playstorerow', models.AutoField(db_column='playStoreRow', primary_key=True, serialize=False)),
                ('gameid', models.IntegerField(db_column='gameID')),
                ('gameprice', models.DecimalField(db_column='gamePrice', decimal_places=2, max_digits=18)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('dateadded', models.DateField(blank=True, db_column='dateAdded', null=True)),
            ],
            options={
                'db_table': 'playstorehistory',
                'managed': False,
            },
        ),
    ]
