# Generated by Django 3.2 on 2021-06-19 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='gameimgurl',
            new_name='gameImgUrl',
        ),
    ]
