# Generated by Django 3.2 on 2021-05-09 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0002_auto_20210509_1434'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game_genre',
        ),
    ]
