# Generated by Django 3.2 on 2021-05-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0004_game_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gamegenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'gamegenre',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Game_genre',
        ),
    ]
