# Generated by Django 3.2 on 2021-06-21 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamelibrary',
            old_name='gameid',
            new_name='game',
        ),
        migrations.AlterUniqueTogether(
            name='gamelibrary',
            unique_together={('game', 'userid')},
        ),
    ]
