# Generated by Django 3.2 on 2021-06-22 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0003_auto_20210621_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelibrary',
            name='lasttimeplayed',
            field=models.DateField(blank=True, db_column='lastTimePlayed', default=datetime.datetime.now, null=True),
        ),
    ]
