# Generated by Django 3.2 on 2021-06-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0004_alter_gamelibrary_lasttimeplayed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelibrary',
            name='lasttimeplayed',
            field=models.DateField(blank=True, db_column='lastTimePlayed', null=True),
        ),
    ]
